CREATE DATABASE IF NOT EXISTS sherine;
USE sherine;


CREATE TABLE IF NOT EXISTS vehicles (
id INT PRIMARY KEY AUTO_INCREMENT,
reg_no VARCHAR(32) NOT NULL UNIQUE,
make VARCHAR(64) NOT NULL,
model VARCHAR(64) NOT NULL,
year INT NOT NULL,
status VARCHAR(32) NOT NULL DEFAULT 'Available'
);